"""Add model tracking to embeddings

Revision ID: cd63829745af
Revises: 6fb5722bc267
Create Date: 2025-12-23 20:17:51.326232

"""
from typing import Sequence, Union

from alembic import op # pyright: ignore[reportMissingImports]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd63829745af'
down_revision: Union[str, Sequence[str], None] = '6fb5722bc267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_embeddings', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('chunk_embeddings', sa.Column('dimensions', sa.Integer(), nullable=True))
    op.drop_column('chunk_embeddings', 'embedding_vector')
    op.add_column('document_chunks', sa.Column('chunk_type', sa.String(length=50), nullable=True))
    op.add_column('document_chunks', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.add_column('document_chunks', sa.Column('start_index', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'end_index')
    op.drop_column('document_chunks', 'start_index')
    op.drop_column('document_chunks', 'meta_data')
    op.drop_column('document_chunks', 'chunk_type')
    op.add_column('chunk_embeddings', sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False)) # type: ignore
    op.drop_column('chunk_embeddings', 'dimensions')
    op.drop_column('chunk_embeddings', 'model_name')
    # ### end Alembic commands ###
