"""add unique constraint to exams

Revision ID: f188f29c58d8
Revises: cd63829745af
Create Date: 2026-01-14 15:17:19.625847

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa
import pgvector # type: ignore


# revision identifiers, used by Alembic.
revision: str = 'f188f29c58d8'
down_revision: Union[str, Sequence[str], None] = 'cd63829745af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_embeddings', sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False))
    op.create_unique_constraint('uq_exam_category', 'exams', ['name', 'board'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exam_category', 'exams', type_='unique')
    op.drop_column('chunk_embeddings', 'embedding_vector')
    # ### end Alembic commands ###
